import Foundation
import SwiftData

/// Represents a task in the to-do list
/// Can be auto-generated or user-created
/// Tapping navigates to relevant screen
@Model
final class ToDoItem {
    var id: UUID
    var title: String
    var taskType: TaskType? // Type of task (for navigation)
    var isCompleted: Bool
    var completedAt: Date?
    var isAutoGenerated: Bool
    var isRecurring: Bool
    var isPersistent: Bool // For expiration reminders that don't reset daily
    var date: Date // due date / next occurrence
    var recurrenceRule: ToDoRecurrence
    var recurrenceWeekday: Int? // 1 = Sunday ... 7 = Saturday
    var autoTaskKey: String? // stable key to avoid auto-task duplicates
    var organizationId: String = "local-default"
    var storeId: String = ""
    var backendId: String?
    var revision: Int = 0
    var updatedByUid: String?
    var lastSyncedAt: Date?
    
    // Relationships
    var relatedItem: InventoryItem?
    var relatedVendor: Vendor?
    
    init(
        title: String,
        taskType: TaskType? = nil,
        isAutoGenerated: Bool,
        isRecurring: Bool = false,
        isPersistent: Bool = false,
        recurrenceRule: ToDoRecurrence = ToDoRecurrence.none,
        recurrenceWeekday: Int? = nil,
        autoTaskKey: String? = nil,
        date: Date = Date(),
        relatedItem: InventoryItem? = nil,
        relatedVendor: Vendor? = nil,
        organizationId: String = "local-default",
        storeId: String = "",
        backendId: String? = nil
    ) {
        self.id = UUID()
        self.title = title
        self.taskType = taskType
        self.isCompleted = false
        self.completedAt = nil
        self.isAutoGenerated = isAutoGenerated
        self.isRecurring = isRecurring
        self.isPersistent = isPersistent
        self.date = date
        self.recurrenceRule = recurrenceRule
        self.recurrenceWeekday = recurrenceWeekday
        self.autoTaskKey = autoTaskKey
        self.relatedItem = relatedItem
        self.relatedVendor = relatedVendor
        self.organizationId = organizationId
        self.storeId = storeId
        self.backendId = backendId
        self.revision = 0
        self.updatedByUid = nil
        self.lastSyncedAt = nil
    }
}

enum ToDoRecurrence: String, Codable, CaseIterable, Identifiable {
    case none = "None"
    case daily = "Daily"
    case weekly = "Weekly"
    
    var id: String { rawValue }
}

/// Types of tasks that navigate to specific screens
enum TaskType: String, Codable {
    case checkExpirations = "Check Expirations"
    case reviewOrders = "Review Orders"
    case spotCheck = "Spot Check"
    case productionSpotCheck = "Production Spot Check"
    case received = "Received"
    case removeExpired = "Remove Expired"
    case truckDelayed = "Truck Delayed"
}
